export const FETCH_OPERATIONS = 'Operations/FETCH_OPERATIONS';
export type FETCH_OPERATIONS = typeof FETCH_OPERATIONS;

export const SET_OPERATIONS = 'Operations/SET_OPERATIONS';
export type SET_OPERATIONS = typeof SET_OPERATIONS;

export const FETCH_OPERATIONS_FAILED = 'Operations/FETCH_OPERATIONS_FAILED';
export type FETCH_OPERATIONS_FAILED = typeof FETCH_OPERATIONS_FAILED;
