export const SET_ITEMS = 'SET_ITEMS';
export const SET_COLUMNS = 'SET_COLUMNS';
export const SET_FILTER = 'SET_FILTER';
export const SET_TAB = 'SET_TAB';
export const SET_LOADING = 'SET_LOADING';
export const INIT_DATA = 'INIT_DATA';
export const SET_NETWORK = 'SET_NETWORK';
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const COMPLETE_FULL_LOAD = 'COMPLETE_FULL_LOAD';
export const SET_AVAILABLE_VALUES = 'SET_AVAILABLE_VALUES';
export const SET_SELECTED_VALUE = 'SET_SELECTED_VALUE';
export const SET_FILTER_COUNT = 'SET_FILTER_COUNT';
export const SET_MODAL_ITEM = 'SET_MODAL_ITEM';
export const SET_SORT = 'SET_SORT';

export const SET_ENTITIES = 'SET_ENTITIES';
export const INIT_ENTITY_PROPERTIES = 'INIT_ENTITY_PROPERTIES';
export const INIT_FILTER = 'INIT_FILTER';

export const INIT_MAIN_PARAMS = 'INIT_MAIN_PARAMS';
export const INIT_ATTRIBUTES = 'INIT_ATTRIBUTES';
