export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_MODAL = 'SET_ITEMS_MODAL';
export const CLEAN_MODAL = 'CLEAN_MODAL';

export const SET_BLOCK_OPERATIONS_MODULE = 'SET_BLOCK_OPERATIONS_MODULE';
