export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';
export const SET_MODAL_ITEMS = 'SET_MODAL_ITEMS';
export const SET_MODAL_SELECTED_ITEM = 'SET_MODAL_SELECTED_ITEM';
export const SET_MODULE = 'SET_MODULE';
export const SET_MODAL_LOADING = 'SET_MODAL_LOADING';
export const SET_MODAL_LOADED = 'SET_MODAL_LOADED';
export const CLEAN_MODAL = 'CLEAN_MODAL';
